# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pydesign.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 804)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.classification_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classification_tab.sizePolicy().hasHeightForWidth())
        self.classification_tab.setSizePolicy(sizePolicy)
        self.classification_tab.setObjectName("classification_tab")
        self.classifier_filepath_field = QtWidgets.QLineEdit(self.classification_tab)
        self.classifier_filepath_field.setGeometry(QtCore.QRect(9, 10, 801, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classifier_filepath_field.sizePolicy().hasHeightForWidth())
        self.classifier_filepath_field.setSizePolicy(sizePolicy)
        self.classifier_filepath_field.setObjectName("classifier_filepath_field")
        self.btn_browse_classification = QtWidgets.QPushButton(self.classification_tab)
        self.btn_browse_classification.setGeometry(QtCore.QRect(825, 9, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_browse_classification.sizePolicy().hasHeightForWidth())
        self.btn_browse_classification.setSizePolicy(sizePolicy)
        self.btn_browse_classification.setObjectName("btn_browse_classification")
        self.groupBox_2 = QtWidgets.QGroupBox(self.classification_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 279, 891, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_classifier_input_data = QtWidgets.QTextEdit(self.groupBox_2)
        self.text_classifier_input_data.setObjectName("text_classifier_input_data")
        self.verticalLayout.addWidget(self.text_classifier_input_data)
        self.groupBox_3 = QtWidgets.QGroupBox(self.classification_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(9, 38, 891, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 151, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.rb_classifier_separator_space = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_classifier_separator_space.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.rb_classifier_separator_space.setObjectName("rb_classifier_separator_space")
        self.rb_classifier_separator_semicolon = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_classifier_separator_semicolon.setGeometry(QtCore.QRect(10, 50, 121, 17))
        self.rb_classifier_separator_semicolon.setObjectName("rb_classifier_separator_semicolon")
        self.rb_classifier_separator_coma = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_classifier_separator_coma.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.rb_classifier_separator_coma.setChecked(True)
        self.rb_classifier_separator_coma.setObjectName("rb_classifier_separator_coma")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(180, 20, 161, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.rb_classifier_missed_calculate = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_classifier_missed_calculate.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.rb_classifier_missed_calculate.setChecked(True)
        self.rb_classifier_missed_calculate.setObjectName("rb_classifier_missed_calculate")
        self.rb_classifier_missed_zeros = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_classifier_missed_zeros.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.rb_classifier_missed_zeros.setObjectName("rb_classifier_missed_zeros")
        self.rb_classifier_missed_ignore = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_classifier_missed_ignore.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.rb_classifier_missed_ignore.setObjectName("rb_classifier_missed_ignore")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(360, 20, 161, 111))
        self.groupBox_6.setObjectName("groupBox_6")
        self.rb_classifier_headers_num = QtWidgets.QRadioButton(self.groupBox_6)
        self.rb_classifier_headers_num.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.rb_classifier_headers_num.setChecked(True)
        self.rb_classifier_headers_num.setObjectName("rb_classifier_headers_num")
        self.rb_classifier_headers_firstrow = QtWidgets.QRadioButton(self.groupBox_6)
        self.rb_classifier_headers_firstrow.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.rb_classifier_headers_firstrow.setObjectName("rb_classifier_headers_firstrow")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_7.setGeometry(QtCore.QRect(540, 20, 161, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.rb_classifier_rowindex_num = QtWidgets.QRadioButton(self.groupBox_7)
        self.rb_classifier_rowindex_num.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.rb_classifier_rowindex_num.setChecked(True)
        self.rb_classifier_rowindex_num.setObjectName("rb_classifier_rowindex_num")
        self.rb_classifier_rowindex_firstcol = QtWidgets.QRadioButton(self.groupBox_7)
        self.rb_classifier_rowindex_firstcol.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.rb_classifier_rowindex_firstcol.setObjectName("rb_classifier_rowindex_firstcol")
        self.rb_classifier_rowindex_lastcol = QtWidgets.QRadioButton(self.groupBox_7)
        self.rb_classifier_rowindex_lastcol.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.rb_classifier_rowindex_lastcol.setObjectName("rb_classifier_rowindex_lastcol")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_8.setGeometry(QtCore.QRect(720, 20, 151, 111))
        self.groupBox_8.setObjectName("groupBox_8")
        self.rb_classifier_labels_firstcol = QtWidgets.QRadioButton(self.groupBox_8)
        self.rb_classifier_labels_firstcol.setGeometry(QtCore.QRect(10, 20, 121, 17))
        self.rb_classifier_labels_firstcol.setObjectName("rb_classifier_labels_firstcol")
        self.rb_classifier_labels__lastcol = QtWidgets.QRadioButton(self.groupBox_8)
        self.rb_classifier_labels__lastcol.setGeometry(QtCore.QRect(10, 50, 121, 17))
        self.rb_classifier_labels__lastcol.setChecked(True)
        self.rb_classifier_labels__lastcol.setObjectName("rb_classifier_labels__lastcol")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(30, 150, 241, 16))
        self.label_6.setObjectName("label_6")
        self.data_to_predict_percent_classifier = QtWidgets.QLineEdit(self.groupBox_3)
        self.data_to_predict_percent_classifier.setGeometry(QtCore.QRect(30, 170, 113, 20))
        self.data_to_predict_percent_classifier.setObjectName("data_to_predict_percent_classifier")
        self.btn_download_classifier_data = QtWidgets.QPushButton(self.classification_tab)
        self.btn_download_classifier_data.setGeometry(QtCore.QRect(10, 250, 891, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_download_classifier_data.sizePolicy().hasHeightForWidth())
        self.btn_download_classifier_data.setSizePolicy(sizePolicy)
        self.btn_download_classifier_data.setObjectName("btn_download_classifier_data")
        self.tabWidget.addTab(self.classification_tab, "")
        self.regression_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regression_tab.sizePolicy().hasHeightForWidth())
        self.regression_tab.setSizePolicy(sizePolicy)
        self.regression_tab.setObjectName("regression_tab")
        self.regression_filepath_field = QtWidgets.QLineEdit(self.regression_tab)
        self.regression_filepath_field.setGeometry(QtCore.QRect(9, 10, 801, 20))
        self.regression_filepath_field.setObjectName("regression_filepath_field")
        self.btn_browse_regression = QtWidgets.QPushButton(self.regression_tab)
        self.btn_browse_regression.setGeometry(QtCore.QRect(825, 9, 75, 23))
        self.btn_browse_regression.setObjectName("btn_browse_regression")
        self.btn_download_regression_data = QtWidgets.QPushButton(self.regression_tab)
        self.btn_download_regression_data.setGeometry(QtCore.QRect(10, 250, 891, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_download_regression_data.sizePolicy().hasHeightForWidth())
        self.btn_download_regression_data.setSizePolicy(sizePolicy)
        self.btn_download_regression_data.setObjectName("btn_download_regression_data")
        self.groupBox_16 = QtWidgets.QGroupBox(self.regression_tab)
        self.groupBox_16.setGeometry(QtCore.QRect(9, 279, 891, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_16.sizePolicy().hasHeightForWidth())
        self.groupBox_16.setSizePolicy(sizePolicy)
        self.groupBox_16.setObjectName("groupBox_16")
        self.text_regression_input_data = QtWidgets.QTextEdit(self.groupBox_16)
        self.text_regression_input_data.setGeometry(QtCore.QRect(10, 20, 871, 411))
        self.text_regression_input_data.setObjectName("text_regression_input_data")
        self.groupBox_10 = QtWidgets.QGroupBox(self.regression_tab)
        self.groupBox_10.setGeometry(QtCore.QRect(9, 38, 891, 201))
        self.groupBox_10.setObjectName("groupBox_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 20, 151, 111))
        self.groupBox_11.setObjectName("groupBox_11")
        self.rb_regression_separator_space = QtWidgets.QRadioButton(self.groupBox_11)
        self.rb_regression_separator_space.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.rb_regression_separator_space.setObjectName("rb_regression_separator_space")
        self.rb_regression_separator_semicilon = QtWidgets.QRadioButton(self.groupBox_11)
        self.rb_regression_separator_semicilon.setGeometry(QtCore.QRect(10, 50, 121, 17))
        self.rb_regression_separator_semicilon.setObjectName("rb_regression_separator_semicilon")
        self.rb_regression_separator_coma = QtWidgets.QRadioButton(self.groupBox_11)
        self.rb_regression_separator_coma.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.rb_regression_separator_coma.setChecked(True)
        self.rb_regression_separator_coma.setObjectName("rb_regression_separator_coma")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_12.setGeometry(QtCore.QRect(180, 20, 161, 111))
        self.groupBox_12.setObjectName("groupBox_12")
        self.rb_regression_missed_calculate = QtWidgets.QRadioButton(self.groupBox_12)
        self.rb_regression_missed_calculate.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.rb_regression_missed_calculate.setChecked(True)
        self.rb_regression_missed_calculate.setObjectName("rb_regression_missed_calculate")
        self.rb_regression_missed_zeros = QtWidgets.QRadioButton(self.groupBox_12)
        self.rb_regression_missed_zeros.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.rb_regression_missed_zeros.setObjectName("rb_regression_missed_zeros")
        self.rb_regression_missed_ignore = QtWidgets.QRadioButton(self.groupBox_12)
        self.rb_regression_missed_ignore.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.rb_regression_missed_ignore.setObjectName("rb_regression_missed_ignore")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_13.setGeometry(QtCore.QRect(360, 20, 161, 111))
        self.groupBox_13.setObjectName("groupBox_13")
        self.rb_regression_headers_num = QtWidgets.QRadioButton(self.groupBox_13)
        self.rb_regression_headers_num.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.rb_regression_headers_num.setChecked(True)
        self.rb_regression_headers_num.setObjectName("rb_regression_headers_num")
        self.rb_regression_headers_firstrow = QtWidgets.QRadioButton(self.groupBox_13)
        self.rb_regression_headers_firstrow.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.rb_regression_headers_firstrow.setObjectName("rb_regression_headers_firstrow")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_14.setGeometry(QtCore.QRect(540, 20, 161, 111))
        self.groupBox_14.setObjectName("groupBox_14")
        self.rb_regression_rowindex_num = QtWidgets.QRadioButton(self.groupBox_14)
        self.rb_regression_rowindex_num.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.rb_regression_rowindex_num.setChecked(True)
        self.rb_regression_rowindex_num.setObjectName("rb_regression_rowindex_num")
        self.rb_regression_rowindex_firstcol = QtWidgets.QRadioButton(self.groupBox_14)
        self.rb_regression_rowindex_firstcol.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.rb_regression_rowindex_firstcol.setObjectName("rb_regression_rowindex_firstcol")
        self.rb_regression_rowindex_lastcol = QtWidgets.QRadioButton(self.groupBox_14)
        self.rb_regression_rowindex_lastcol.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.rb_regression_rowindex_lastcol.setObjectName("rb_regression_rowindex_lastcol")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_15.setGeometry(QtCore.QRect(720, 20, 151, 111))
        self.groupBox_15.setObjectName("groupBox_15")
        self.rb_regression_labels_firstcol = QtWidgets.QRadioButton(self.groupBox_15)
        self.rb_regression_labels_firstcol.setGeometry(QtCore.QRect(10, 20, 121, 17))
        self.rb_regression_labels_firstcol.setObjectName("rb_regression_labels_firstcol")
        self.rb_regression_labels__lastcol = QtWidgets.QRadioButton(self.groupBox_15)
        self.rb_regression_labels__lastcol.setGeometry(QtCore.QRect(10, 50, 121, 17))
        self.rb_regression_labels__lastcol.setChecked(True)
        self.rb_regression_labels__lastcol.setObjectName("rb_regression_labels__lastcol")
        self.label_13 = QtWidgets.QLabel(self.groupBox_10)
        self.label_13.setGeometry(QtCore.QRect(10, 135, 241, 31))
        self.label_13.setObjectName("label_13")
        self.data_to_predict_percent_regression = QtWidgets.QLineEdit(self.groupBox_10)
        self.data_to_predict_percent_regression.setGeometry(QtCore.QRect(10, 170, 113, 20))
        self.data_to_predict_percent_regression.setObjectName("data_to_predict_percent_regression")
        self.label_5 = QtWidgets.QLabel(self.groupBox_10)
        self.label_5.setGeometry(QtCore.QRect(370, 150, 101, 16))
        self.label_5.setObjectName("label_5")
        self.target_columns_line_regression = QtWidgets.QLineEdit(self.groupBox_10)
        self.target_columns_line_regression.setGeometry(QtCore.QRect(370, 170, 113, 20))
        self.target_columns_line_regression.setObjectName("target_columns_line_regression")
        self.tabWidget.addTab(self.regression_tab, "")
        self.clasterization_tab = QtWidgets.QWidget()
        self.clasterization_tab.setObjectName("clasterization_tab")
        self.gb_clustering_settings = QtWidgets.QGroupBox(self.clasterization_tab)
        self.gb_clustering_settings.setGeometry(QtCore.QRect(10, 20, 881, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_clustering_settings.sizePolicy().hasHeightForWidth())
        self.gb_clustering_settings.setSizePolicy(sizePolicy)
        self.gb_clustering_settings.setObjectName("gb_clustering_settings")
        self.label = QtWidgets.QLabel(self.gb_clustering_settings)
        self.label.setGeometry(QtCore.QRect(200, 20, 101, 16))
        self.label.setObjectName("label")
        self.clusters = QtWidgets.QLineEdit(self.gb_clustering_settings)
        self.clusters.setEnabled(False)
        self.clusters.setGeometry(QtCore.QRect(310, 20, 31, 20))
        self.clusters.setText("")
        self.clusters.setObjectName("clusters")
        self.label_2 = QtWidgets.QLabel(self.gb_clustering_settings)
        self.label_2.setGeometry(QtCore.QRect(200, 50, 81, 31))
        self.label_2.setObjectName("label_2")
        self.checkBox_kmeans = QtWidgets.QCheckBox(self.gb_clustering_settings)
        self.checkBox_kmeans.setGeometry(QtCore.QRect(20, 20, 131, 17))
        self.checkBox_kmeans.setObjectName("checkBox_kmeans")
        self.checkBox_tsne = QtWidgets.QCheckBox(self.gb_clustering_settings)
        self.checkBox_tsne.setGeometry(QtCore.QRect(20, 50, 101, 17))
        self.checkBox_tsne.setObjectName("checkBox_tsne")
        self.checkBox_dbscan = QtWidgets.QCheckBox(self.gb_clustering_settings)
        self.checkBox_dbscan.setGeometry(QtCore.QRect(20, 80, 111, 17))
        self.checkBox_dbscan.setObjectName("checkBox_dbscan")
        self.btn_start_clustering = QtWidgets.QPushButton(self.gb_clustering_settings)
        self.btn_start_clustering.setGeometry(QtCore.QRect(650, 30, 131, 61))
        self.btn_start_clustering.setObjectName("btn_start_clustering")
        self.data_to_predict = QtWidgets.QLineEdit(self.gb_clustering_settings)
        self.data_to_predict.setEnabled(False)
        self.data_to_predict.setGeometry(QtCore.QRect(310, 60, 113, 20))
        self.data_to_predict.setText("")
        self.data_to_predict.setObjectName("data_to_predict")
        self.label_14 = QtWidgets.QLabel(self.gb_clustering_settings)
        self.label_14.setGeometry(QtCore.QRect(200, 90, 71, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtWidgets.QLineEdit(self.gb_clustering_settings)
        self.lineEdit.setGeometry(QtCore.QRect(310, 90, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox = QtWidgets.QGroupBox(self.clasterization_tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 881, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.text_clustering_input_data = QtWidgets.QTextEdit(self.groupBox)
        self.text_clustering_input_data.setGeometry(QtCore.QRect(10, 60, 431, 441))
        self.text_clustering_input_data.setObjectName("text_clustering_input_data")
        self.text_clustering_output_data = QtWidgets.QTextEdit(self.groupBox)
        self.text_clustering_output_data.setGeometry(QtCore.QRect(450, 60, 421, 441))
        self.text_clustering_output_data.setObjectName("text_clustering_output_data")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(450, 40, 101, 16))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.clasterization_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.logs_label = QtWidgets.QLabel(self.centralwidget)
        self.logs_label.setText("")
        self.logs_label.setObjectName("logs_label")
        self.gridLayout_2.addWidget(self.logs_label, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Машинне навчання"))
        self.btn_browse_classification.setText(_translate("MainWindow", "Обрати файл"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Вхідні дані"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Налаштування"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Роздільник"))
        self.rb_classifier_separator_space.setText(_translate("MainWindow", "Пробіл \' \'"))
        self.rb_classifier_separator_semicolon.setText(_translate("MainWindow", "Крапка з комою \';\'"))
        self.rb_classifier_separator_coma.setText(_translate("MainWindow", "Кома \',\'"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Пропущені значення"))
        self.rb_classifier_missed_calculate.setText(_translate("MainWindow", "Розрахувати"))
        self.rb_classifier_missed_zeros.setText(_translate("MainWindow", "Замінити на 0"))
        self.rb_classifier_missed_ignore.setText(_translate("MainWindow", "Ігнорувати"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Заголовки таблиці"))
        self.rb_classifier_headers_num.setText(_translate("MainWindow", "За номером"))
        self.rb_classifier_headers_firstrow.setText(_translate("MainWindow", "Перший рядок"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Індекси рядків"))
        self.rb_classifier_rowindex_num.setText(_translate("MainWindow", "За номером"))
        self.rb_classifier_rowindex_firstcol.setText(_translate("MainWindow", "Перший стовпець"))
        self.rb_classifier_rowindex_lastcol.setText(_translate("MainWindow", "Останній стовпець"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Цільові значення (мітки)"))
        self.rb_classifier_labels_firstcol.setText(_translate("MainWindow", "Перший стовпець"))
        self.rb_classifier_labels__lastcol.setText(_translate("MainWindow", "Останній стовпець"))
        self.label_6.setText(_translate("MainWindow", "Частина початкових даних для передбачення"))
        self.data_to_predict_percent_classifier.setPlaceholderText(_translate("MainWindow", "0.2"))
        self.btn_download_classifier_data.setText(_translate("MainWindow", "Обробити дані"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.classification_tab), _translate("MainWindow", "Класифікація"))
        self.btn_browse_regression.setText(_translate("MainWindow", "Обрати файл"))
        self.btn_download_regression_data.setText(_translate("MainWindow", "Обробити дані"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Вхідні дані"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Налаштування"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Роздільник"))
        self.rb_regression_separator_space.setText(_translate("MainWindow", "Пробіл \' \'"))
        self.rb_regression_separator_semicilon.setText(_translate("MainWindow", "Крапка з комою \';\'"))
        self.rb_regression_separator_coma.setText(_translate("MainWindow", "Кома \',\'"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Пропущені значення"))
        self.rb_regression_missed_calculate.setText(_translate("MainWindow", "Розрахувати"))
        self.rb_regression_missed_zeros.setText(_translate("MainWindow", "Замінити на 0"))
        self.rb_regression_missed_ignore.setText(_translate("MainWindow", "Ігнорувати"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Заголовки таблиці"))
        self.rb_regression_headers_num.setText(_translate("MainWindow", "За номером"))
        self.rb_regression_headers_firstrow.setText(_translate("MainWindow", "Перший рядок"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Ярлики рядків"))
        self.rb_regression_rowindex_num.setText(_translate("MainWindow", "За номером"))
        self.rb_regression_rowindex_firstcol.setText(_translate("MainWindow", "Перший стовпець"))
        self.rb_regression_rowindex_lastcol.setText(_translate("MainWindow", "Останній стовпець"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Цільові значення (мітки)"))
        self.rb_regression_labels_firstcol.setText(_translate("MainWindow", "Перший стовпець"))
        self.rb_regression_labels__lastcol.setText(_translate("MainWindow", "Останній стовпець"))
        self.label_13.setText(_translate("MainWindow", "Частина початкових даних \n"
"для передбаченя"))
        self.data_to_predict_percent_regression.setPlaceholderText(_translate("MainWindow", "0.2"))
        self.label_5.setText(_translate("MainWindow", "Цільовий стовпець"))
        self.target_columns_line_regression.setPlaceholderText(_translate("MainWindow", "155"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.regression_tab), _translate("MainWindow", "Регресія"))
        self.gb_clustering_settings.setTitle(_translate("MainWindow", "НАЛАШТУВАННЯ"))
        self.label.setText(_translate("MainWindow", "Кількість кластерів"))
        self.clusters.setPlaceholderText(_translate("MainWindow", "3"))
        self.label_2.setText(_translate("MainWindow", "Дані для \n"
"передбачення"))
        self.checkBox_kmeans.setText(_translate("MainWindow", "Метод К-середніх"))
        self.checkBox_tsne.setText(_translate("MainWindow", "Метод t-SNE"))
        self.checkBox_dbscan.setText(_translate("MainWindow", "Метод DBSCAN"))
        self.btn_start_clustering.setText(_translate("MainWindow", "Старт"))
        self.data_to_predict.setPlaceholderText(_translate("MainWindow", "n1 n2 n3 n4"))
        self.label_14.setText(_translate("MainWindow", "Номера осей"))
        self.lineEdit.setText(_translate("MainWindow", "0 1"))
        self.groupBox.setTitle(_translate("MainWindow", "РЕЗУЛЬТАТИ"))
        self.label_3.setText(_translate("MainWindow", "Вхідні дані"))
        self.label_4.setText(_translate("MainWindow", "Передбачені дані"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.clasterization_tab), _translate("MainWindow", "Кластерізація"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
